### ISSUE TITLE
Summary.txt :scream: :scream: :scream:

### ISSUE THREAD

**Issue by RudeBit4** [RudeBit4/GeekGamesShop#8]

**Comment by JohnnyLviv** [comment]
> Що будемо писати, м?

**Comment by RudeBit4** [comment]
@JohnnyLviv НЗ

**Comment by RudeBit4** [comment]
3 Практична | 4 Практична
------------ | -------------
удосконалила навички створення та наповнення власного репозиторію| удосконалила навички створення та наповнення проекту у репозиторії
